export { getCurrentUser, loginUser, registerUser } from './auth'
export { API_BASE_URL, ApiError, apiClient, setOnUnauthorized } from './client'
export { getApiErrorMessage } from './errors'
export { getPlaylistById, getFavorites, listPlaylists } from './playlists'
export { getTrackById, listTracks } from './tracks'
export { listGenres } from './genres'
export { listArtists } from './artists'
export { getProfile, saveOnboarding } from './onboarding'
export { trackEvent, toggleLikeTrack } from './events'
export { listTrackRecommendations, listPlaylistRecommendations } from './recommendations'
