"""Seed: download Deezer preview MP3s to frontend/public/audio/
and generate SQL migration. Tracks stored locally — no expiring tokens.

Usage:
    python scripts/seed_deezer.py [--limit 4]
"""

import argparse, json, sys, time, os, urllib.request, urllib.parse, io

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

DEEZER_API = "https://api.deezer.com"
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
AUDIO_DIR = os.path.join(SCRIPT_DIR, "..", "frontend", "public", "audio")

GENRES = ["pop", "rock", "hip-hop", "electronic", "jazz",
          "classical", "rnb", "country", "metal", "indie"]
GENRE_MAP = {"hip-hop": "hip hop"}


def fetch_tracks(genre, limit):
    q = urllib.parse.quote(f'genre:"{GENRE_MAP.get(genre, genre)}"')
    url = f"{DEEZER_API}/search?q={q}&limit={limit}"
    print(f"  {genre}: {url[:80]}...", file=sys.stderr)
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=15) as r:
        data = json.loads(r.read())
    return data.get("data", [])


def download_mp3(url, filepath, timeout=20):
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req, timeout=timeout) as r:
            data = r.read()
            os.makedirs(os.path.dirname(filepath), exist_ok=True)
            with open(filepath, "wb") as f:
                f.write(data)
            return len(data)
    except Exception as e:
        print(f"    SKIP: {e}", file=sys.stderr)
        return None


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=4)
    args = parser.parse_args()

    os.makedirs(AUDIO_DIR, exist_ok=True)
    all_artists = {}
    all_tracks = []
    seen_ids = set()
    track_id = 100
    artist_id = 100
    genre_name_id = {g: i + 1 for i, g in enumerate(GENRES)}
    used_artists = set()

    for genre in GENRES:
        tracks = fetch_tracks(genre, args.limit)
        for t in tracks:
            dz_id = t.get("id")
            preview = t.get("preview", "")
            if not dz_id or dz_id in seen_ids or not preview:
                continue
            seen_ids.add(dz_id)

            artist_raw = t.get("artist", {}).get("name", "Unknown")
            artist_name = artist_raw.replace("'", "''").encode("ascii", "ignore").decode("ascii")
            if artist_name not in used_artists:
                used_artists.add(artist_name)
                all_artists[artist_name] = artist_id
                artist_id += 1

            title_raw = t.get("title", "Untitled")
            title = title_raw.replace("'", "''").encode("ascii", "ignore").decode("ascii")
            duration = t.get("duration", 30)
            local = f"track-{track_id}.mp3"
            local_path = os.path.join(AUDIO_DIR, local)

            print(f"  Download {track_id} ({title[:25]})...", file=sys.stderr)
            size = download_mp3(preview, local_path)
            if size is None:
                continue
            print(f"    OK: {size // 1000}KB", file=sys.stderr)

            all_tracks.append({
                "id": track_id,
                "title": title,
                "artist_name": artist_name,
                "duration_ms": duration * 1000,
                "preview_url": f"/audio/{local}",
                "cover_url": t.get("album", {}).get("cover_medium", ""),
                "popularity": 50,
                "source_genre": genre,
            })
            track_id += 1
            time.sleep(0.1)

    # SQL output
    print("-- Generated by seed_deezer.py (local MP3s)")
    print()

    if all_artists:
        print("DELETE FROM track_genres WHERE track_id >= 100;")
        print("DELETE FROM tracks WHERE id >= 100;")
        print("DELETE FROM artists WHERE id >= 100;")
        print()
        print("INSERT INTO artists (id, name, image_url) VALUES")
        rows = []
        for name, aid in sorted(all_artists.items(), key=lambda x: x[1]):
            rows.append(f"    ({aid}, '{name}', 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400')")
        print(",\n".join(rows))
        print("ON CONFLICT (name) DO NOTHING;")
        print()

    if all_tracks:
        print("INSERT INTO tracks (id, title, artist_id, duration_ms, preview_url, cover_url, popularity_score) VALUES")
        rows = []
        for tr in all_tracks:
            p = f"'{tr['preview_url']}'"
            c = f"'{tr['cover_url']}'" if tr.get('cover_url') else "NULL"
            rows.append(f"    ({tr['id']}, '{tr['title']}', {all_artists[tr['artist_name']]}, {tr['duration_ms']}, {p}, {c}, {tr['popularity']})")
        print(",\n".join(rows))
        print("ON CONFLICT (id) DO UPDATE SET preview_url=EXCLUDED.preview_url;")
        print()

        print("INSERT INTO track_genres (track_id, genre_id) VALUES")
        g_rows = []
        for tr in all_tracks:
            gid = genre_name_id.get(tr['source_genre'])
            if gid:
                g_rows.append(f"    ({tr['id']}, {gid})")
        if g_rows:
            print(",\n".join(g_rows))
            print("ON CONFLICT (track_id, genre_id) DO NOTHING;")
        print()

        print(f"SELECT setval('artists_id_seq', {max(all_artists.values()) + 10});")
        print(f"SELECT setval('tracks_id_seq', {len(all_tracks) + 10});")
        print()
        print(f"-- Downloaded {len(all_tracks)} MP3s to {AUDIO_DIR}")


if __name__ == "__main__":
    main()
